### ISSUE TITLE
🚀 Feature: Security enhancements

### ISSUE THREAD

**Issue by yurimutti** [detrash/recy-network#170]
### 🔖 Feature description

Add Frontend Security enhancements by integrating support for reCAPTCHA and Cloudflare to protect against spam, bots, and DDoS attacks.

### 🎤 Why is this feature needed ?

In my use case, the application is exposed to potential abuse, such as fake account creation, brute force attacks, or API misuse. By implementing reCAPTCHA and leveraging Cloudflare's security features, the frontend can prevent automated malicious behavior while ensuring legitimate users have a smooth experience.

### ✌️ How do you aim to achieve this?

Add reCAPTCHA support (v2 or v3) for critical forms (e.g., login, signup, or feedback forms).
Provide Cloudflare integration to protect frontend assets and APIs from malicious traffic, including rate limiting and bot detection.
Offer easy configuration options for enabling or customizing these features.

### 🔄️ Additional Information

Alternative solutions, such as custom bot detection or IP blacklisting, are harder to maintain and less effective compared to established services like reCAPTCHA and Cloudflare. Integrating these directly would reduce complexity and improve overall security.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/detrash/recy-network/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by yurimutti** [comment]
@Lucas-Bento-D  it's interesting to write your thoughts for this implementation.

**Comment by Lucas-Bento-D** [comment]
About this feature: 

We need of generation of keys(sitekey and secretkey) of cloudflare;
On front-end, We will use sitekey to render a captcha component on forms(signup, login and others forms), where the success token, will to send this token to a back end endpoint. On back-end, we will to create a endpoint to verification a token on "turnstile/v0/siteverify" of cloudflare endpoint.

docs:
https://developers.cloudflare.com/turnstile/get-started/
https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/
https://developers.cloudflare.com/turnstile/get-started/server-side-validation/
